"""Independently archived, label-blind literature replay contracts."""

from vaxreplay.literature.adapter import (
    BuiltLiteratureEpisode,
    LiteratureAdmissionError,
    VerifiedDecisionPackage,
    VerifiedOutcomePackage,
    build_literature_episode,
    make_release_source_material_verifier,
    verify_decision_package,
    verify_outcome_package,
)
from vaxreplay.literature.schema import (
    ArchivedLiteratureDocument,
    ArchiveProof,
    CandidatePanelManifest,
    CorpusExclusion,
    DecisionSeal,
    ExtractionRunManifest,
    LiteratureByteSpan,
    LiteratureClaim,
    LiteratureCorpusManifest,
    LiteratureDecisionPackage,
    LiteratureEvaluationConfig,
    LiteratureOutcomeJoinAudit,
    LiteratureOutcomePackage,
    LiteratureSourceAudit,
    LiteratureSourceFileBinding,
    OutcomeJoinRecord,
    PanelCandidate,
    PanelExclusion,
    literature_decision_content_sha256,
    literature_decision_package_sha256,
    literature_model_sha256,
    literature_outcome_package_sha256,
)

LiteratureEpisodeSpec = LiteratureEvaluationConfig

__all__ = [
    'ArchiveProof',
    'ArchivedLiteratureDocument',
    'BuiltLiteratureEpisode',
    'CandidatePanelManifest',
    'CorpusExclusion',
    'DecisionSeal',
    'ExtractionRunManifest',
    'LiteratureByteSpan',
    'LiteratureAdmissionError',
    'LiteratureClaim',
    'LiteratureCorpusManifest',
    'LiteratureDecisionPackage',
    'LiteratureEvaluationConfig',
    'LiteratureEpisodeSpec',
    'LiteratureOutcomeJoinAudit',
    'LiteratureOutcomePackage',
    'LiteratureSourceAudit',
    'LiteratureSourceFileBinding',
    'OutcomeJoinRecord',
    'PanelCandidate',
    'PanelExclusion',
    'VerifiedDecisionPackage',
    'VerifiedOutcomePackage',
    'build_literature_episode',
    'literature_decision_content_sha256',
    'literature_decision_package_sha256',
    'literature_model_sha256',
    'literature_outcome_package_sha256',
    'make_release_source_material_verifier',
    'verify_decision_package',
    'verify_outcome_package',
]
